### PR TITLE
Display implementation completion diagram

### PR DESCRIPTION
**Pull request by delvh**
Closes #c39be98c-b6e8-4cf0-b04e-47aa07de2024

### CODE REVIEW

**Comment by nk-coding** [comment]
my poor .gitkeep
well, either the gitkeep or you need to adapt the generation script to create the folder if not existing

**Comment by delvh** [comment]
Seemed to me as if there was already something in the directory.
But I probably already executed `npm run render-diagrams` at some point already.

**Review by nk-coding — DISMISSED** [review]
imho it would be a good idea to also update the other diagram files
the main purpose of the config variables at the top is to only have to maintain one version of the diagram, and just set the config variables correctly for the different versions

**Review by nk-coding — APPROVED** [review]
better

**Pull request merged**
